/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libfreenect_KinectLed */

#ifndef _Included_com_libfreenect_KinectLed
#define _Included_com_libfreenect_KinectLed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libfreenect_KinectLed
 * Method:    commitLEDToDevice
 * Signature: (Lcom/libfreenect/LEDStatus;)V
 */
JNIEXPORT void JNICALL Java_com_libfreenect_KinectLed_commitLEDToDevice
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
