/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_libfreenect_KinectDevice */

#ifndef _Included_com_libfreenect_KinectDevice
#define _Included_com_libfreenect_KinectDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libfreenect_KinectDevice
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libfreenect_KinectDevice_connect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
