/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libfreenect_KinectRGBCamera */

#ifndef _Included_com_libfreenect_KinectRGBCamera
#define _Included_com_libfreenect_KinectRGBCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libfreenect_KinectRGBCamera
 * Method:    captureRawImage
 * Signature: ()[I
 */
JNIEXPORT void JNICALL Java_com_libfreenect_KinectRGBCamera_captureRawImage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
