/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libfreenect_KinectMotor */

#ifndef _Included_com_libfreenect_KinectMotor
#define _Included_com_libfreenect_KinectMotor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libfreenect_KinectMotor_minimumPositionBoundary
#define com_libfreenect_KinectMotor_minimumPositionBoundary 0.0
#undef com_libfreenect_KinectMotor_maximumPositionBoundary
#define com_libfreenect_KinectMotor_maximumPositionBoundary 1.0
/*
 * Class:     com_libfreenect_KinectMotor
 * Method:    commitPositionToDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libfreenect_KinectMotor_commitPositionToDevice
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
